### ISSUE TITLE
Got these error 

### ISSUE THREAD

**Issue by saran0008** [mith36/XSS-PrO#3]
Traceback (most recent call last):
  File "/home/user/XSS-PrO/XSS_PRO.py", line 114, in <module>
    popup_triggered, alert_text = check_popup(url_with_payload, payload)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hacker/XSS-PrO/XSS_PRO.py", line 46, in check_popup
    driver = get_chrome_driver()
             ^^^^^^^^^^^^^^^^^^^
  File "/home/user/XSS-PrO/XSS_PRO.py", line 27, in get_chrome_driver
    chrome_driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/remote/webdriver.py", line 212, in __init__
    self.start_session(capabilities)
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/remote/webdriver.py", line 299, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x563c3c7eb6ba <unknown>
#1 0x563c3c4bb730 <unknown>
#2 0x563c3c4f3615 <unknown>
#3 0x563c3c4ef488 <unknown>
#4 0x563c3c539e88 <unknown>
#5 0x563c3c52d7f3 <unknown>
#6 0x563c3c4fdec9 <unknown>
#7 0x563c3c4fe91e <unknown>
#8 0x563c3c7b19eb <unknown>
#9 0x563c3c7b5972 <unknown>
#10 0x563c3c79ee15 <unknown>
#11 0x563c3c7b6502 <unknown>
#12 0x563c3c783d2f <unknown>
#13 0x563c3c7da578 <unknown>
#14 0x563c3c7da750 <unknown>
#15 0x563c3c7ea48c <unknown>
#16 0x7fd0e6b56dbb <unknown>

**Comment by mith36** [comment]
check whether you have a chrome browser installed. if not install it

**Comment by saran0008** [comment]
I installed in wsl even though it is not working bro

**Comment by mith36** [comment]
Try running in your Windows machine.
This issue is because it's not able to launch the Chrome browser.
It could be an issue with the web driver library version also so, I have updated the **requirements.txt file** with the library version.

**Comment by saran0008** [comment]
Ok, I will try.

**Comment by mith36** [comment]
I have made a few changes to the code. also, i have added the Chrome web driver

just clone the new code and run it

**Comment by saran0008** [comment]
Great!
