### ISSUE TITLE
Issue xss not works 

### ISSUE THREAD

**Issue by uskolor** [mith36/XSS-PrO#5]
HI 
I appreciate your effort but it still doesn't work. The errors I get in Terminal

-------------
pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

------------------------
Traceback (most recent call last):
  File "/home/ugiel/XSS-PrO/XSS_PRO.py", line 114, in <module>
    popup_triggered, alert_text = check_popup(url_with_payload, payload)
  File "/home/giel/XSS-PrO/XSS_PRO.py", line 46, in check_popup
    driver = get_chrome_driver()
  File "/home/giel/XSS-PrO/XSS_PRO.py", line 27, in get_chrome_driver
    chrome_driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
  File "/home/ugiel/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/ugiel/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)

**Comment by mith36** [comment]
Hi
sorry to hear this, the issue mentioned **ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'**   is from your side only.
Please check the directory to see if you have requirements.txt in your folder.

Run on Windows machine because the chrome driver I uploaded here is for Windows.

**Comment by uskolor** [comment]
I use this only in Terminal whee is Linux.
